redis:
  host: localhost
  port: 6379
  password: ''

configuration:
  server: lobby/01

settings:
  default_preview_items:
    material: DIAMOND_SWORD
    amount: 1
    customModelData: 0
    display: "<color:#03BA00>ไอเทมตัวอย่าง"
    lore:
      - "<gray>คุณสามารถแก้ไขไอเทมตัวอย่างนี้"
      - "<gray>ได้โดยการลากไอเทมมาวางทับในหน้าจัดการ"
  rewards_lore:
    - ""
    - "<color:#FFE92F>[Q] <red>เพื่อทำการลบไอเทมออก"
    - "<color:#FFE92F>[▶] <gray>คลิก <color:#FFE92F>ซ้าย <gray>เพื่อทำการแก้ไขไอเทม"